<a href="https://colab.research.google.com/github/paulagirones/Aerogels_thermal_conductivity/blob/main/aerogels_thermal_conductivity_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aerogels thermal conductivity

# DATA EXPLORATION

In [60]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('20250220_dataset.csv')

# Inspect the first rows
print("First 5 rows:")
display(df.head())

# Display information about the dataset
print("\nDataset information:")
df.info()

First 5 rows:

,Entry,Drying,Purpose,Shape,First materials,Second materials,Modification,First material class,Second materials class,Modification class,...,BET surface area m2/g,BJH pore size nm,BJH pore volume (total) cm3/g,compression elastic modulus MPa,SEM,Thermal conductivity W/(m K),Thermal method,Thermal method detail,Unnamed: 28,Unnamed: 29
0,1,SCD,Not specific,Monolith?,Soda soap,NaN,NaN,Q,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16559 entries, 0 to 16558
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Entry                            16559 non-null  int64
 1   Drying                           16559 non-null  object
 2   Purpose                          16559 non-null  object
 3   Shape                            16559 non-null  object
 4   First materials                  16559 non-null  object
 5   Second materials                 6368 non-null   object
 6   Modification                     3086 non-null   object
 7   First material class             16559 non-null  object
 8   Second materials class           6368 non-null   object
 9   Modification class               3082 non-null   object
 10  Gelation class                   16559 non-null  object
 11  Solvent class                    16559 non-null  object
 12  Process                          16559 non-null  object
 13  Gelation mechanism               16559 non-null  object
 14  Final solvent                    16559 non-null  object
 15  Drying details                   16559 non-null  object
 16  Post drying treatment            3295 non-null   object
 17  Post-drying cross-linking        495 non-null    object
 18  Envelope density g/cm3           10755 non-null  float64
 19  Porosity                         7122 non-null   object
 20  BET surface area m2/g            7483 non-null   float64
 21  BJH pore size nm                 1012 non-null   float64
 22  BJH pore volume (total) cm3/g    2479 non-null   float64
 23  compression elastic modulus MPa  3001 non-null   float64
 24  SEM                              15605 non-null  object
 25  Thermal conductivity W/(m K)     2484 non-null   float64
 26  Thermal method                   2493 non-null   object
 27  Thermal method detail            2490 non-null   object
 28  Unnamed: 28                      0 non-null      float64
 29  Unnamed: 29                      29 non-null     object
dtypes: float64(7), int64(1), object(22)
memory usage: 3.8+ MB

# CLEANING AND PRE-PROCESSING

In [63]:
# Check Porosity type
print('Porosity type:')
print(df['Porosity'].dtype)
print(df['Porosity'].unique()[:20])

# Check SEM type
print('SEM type:')
print(df['SEM'].dtype)
print(df['SEM'].unique()[:20])


# Check Unnamed:29 type and content
print('Unnamed: 29 column content:')
print(df['Unnamed: 29'].dtype)
print(df['Unnamed: 29'].unique())

Porosity type:
object
[nan '95%' '94%' '98%' '96%' '97%' '65%' '74.38%' '80.75%' '84.19%'
 '88.06%' '87.45%' '82.64%' '78.32%' '67.97%' '32.80%' '48.20%' '53.70%'
 '59.30%' '65.90%']
SEM type:
object
[nan 'Mesoporous (nanoparticulate)' 'Macroporous (cellular)' 'Mesoporous?'
 'Macroporous (flakes)' 'Macroporous (particulate)'
 'Macroporous (fibrous)' 'Macroporous (fibrous and particulate)'
 'Mesoporous (nanofibrous)' 'Microparticles'
 'Macroporous (cellular and fibrous)'
 'Mesoporous (nanofibrous and nanoparticulate)'
 'Macroporous (cellular and flakes)' 'Macroporous (fibrous and flakes)'
 'Macroporous (nanoparticulate)' 'Macroporous (cellular and particulate)'
 'Macroporous (flakes and particulate)' 'Macroporous' 'Macroporous?'
 'Macroporous (nanofibrous)']
Unnamed: 29 column content:
object
[nan 'kokoko' 'koko' 'kokokoko' 'kokokokoko']

In [64]:
#Fix porosity type (it is numeric)
df['Porosity'] = (
    df['Porosity']
    .str.replace('%', '', regex=False)
    .astype(float)
)

display(df['Porosity'].describe())

# Remove empty and wrong columns
df = df.drop(columns=['Unnamed: 28', 'Unnamed: 29'])

count    7122.000000
mean       87.895411
std        14.065184
min         0.530000
25%        85.000000
50%        92.500000
75%        97.100000
max       100.000000
Name: Porosity, dtype: float64

In [65]:
# Check missing values
missing = pd.DataFrame({
    'Missing values': df.isna().sum(),
    'Missing (%)': df.isna().mean() * 100
})
display(missing.sort_values('Missing (%)', ascending=False))

# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")

                                 Missing values  Missing (%)
Post-drying cross-linking                 16064    97.010689
BJH pore size nm                          15547    93.888520
BJH pore volume (total) cm3/g             14080    85.029289
Thermal conductivity W/(m K)              14075    84.999094
Thermal method detail                     14069    84.962860
Thermal method                            14066    84.944743
compression elastic modulus MPa           13558    81.876925
Modification class                        13477    81.387765
Modification                              13473    81.363609
Post drying treatment                     13264    80.101455
Second materials                          10191    61.543571
Second materials class                    10191    61.543571
Porosity                                   9437    56.990156
BET surface area m2/g                      9076    54.810073
Envelope density g/cm3                     5804    35.050426
SEM                                         954     5.761217
Entry                                         0     0.000000
Drying                                        0     0.000000
Purpose                                       0     0.000000
Shape                                         0     0.000000
Solvent class                                 0     0.000000
Gelation class                                0     0.000000
First materials                               0     0.000000
First material class                          0     0.000000
Process                                       0     0.000000
Gelation mechanism                            0     0.000000
Final solvent                                 0     0.000000
Drying details                                0     0.000000

Duplicate rows: 0

In [66]:
#Rename columns
df = df.rename(columns={
    'Thermal conductivity W/(m K)': 'Thermal_conductivity',
    'Envelope density g/cm3': 'Density',
    'BET surface area m2/g': 'BET',
    'BJH pore size nm': 'Pore_size',
    'BJH pore volume (total) cm3/g': 'Pore_volume',
    'compression elastic modulus MPa': 'Elastic_modulus'
})

# Remove samples without a measured thermal conductivity (our target)
df = df.dropna(subset=['Thermal_conductivity'])

# Replace missing categorical values with "Unknown"
categorical_columns = df.select_dtypes(include='object').columns
df[categorical_columns] = df[categorical_columns].fillna('Unknown')

#Dataset after cleaning
print(f"Dataset after cleaning: {df.shape}")

missing = pd.DataFrame({
    'Missing values': df.isna().sum(),
    'Missing (%)': df.isna().mean() * 100
})
display(missing.sort_values('Missing (%)', ascending=False))

Dataset after cleaning: (2484, 28)

                           Missing values  Missing (%)
Pore_size                            2324    93.558776
Pore_volume                          2166    87.198068
Elastic_modulus                      1657    66.706924
BET                                  1525    61.392915
Porosity                             1079    43.438003
Density                               274    11.030596
First materials                         0     0.000000
Second materials                        0     0.000000
Entry                                   0     0.000000
Drying                                  0     0.000000
Purpose                                 0     0.000000
Shape                                   0     0.000000
Solvent class                           0     0.000000
Gelation class                          0     0.000000
Modification class                      0     0.000000
Second materials class                  0     0.000000
First material class                    0     0.000000
Modification                            0     0.000000
Process                                 0     0.000000
Gelation mechanism                      0     0.000000
Post drying treatment                   0     0.000000
Post-drying cross-linking               0     0.000000
Final solvent                           0     0.000000
Drying details                          0     0.000000
SEM                                     0     0.000000
Thermal_conductivity                    0     0.000000
Thermal method                          0     0.000000
Thermal method detail                   0     0.000000

In [71]:
# Display categories and number of unique values
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(f"Number of categories: {df[col].nunique()}")
    print(df[col].unique()[:20])

--- Drying ---
Number of categories: 5
['SCD' 'FD' 'APD' 'VD' 'Foaming']

--- Purpose ---
Number of categories: 28
['Thermal insulation' 'Not specific'
 'Sound insulation, thermal insulation' 'Adsorbent' 'Filters' 'Separation'
 'Adsorbent (gas)' 'Thermoelectric devices' 'Steam generation'
 'Separation, thermal insulation' 'Adsorbent, thermal insulation'
 'PCM support' 'Separation, thermal Insulation' 'Sound insulation'
 'Filters, thermal insulation' 'Sensors, thermal insulation'
 'Optoelectronic devices' 'Shield, thermal insulation' 'Packaging'
 'Adsorbent (gas), sensors']

--- Shape ---
Number of categories: 11
['Monolith' 'Fibers, monolith' 'Monolith ' 'Sheet' 'Fibers'
 'Monolith, sheet' 'Monolith (3D)' 'Beads, monolith' 'Beads' 'FIbers'
 'Coating']

--- First materials ---
Number of categories: 90
['RF' 'Phenolic resin' 'Polyisocyanurate' 'Polyurethane'
 'Polydicyclopentadiene' 'Poly(urea-urethane)' 'Aramid fibers' 'Polyimide'
 'Lignocellulose' 'Cellulose' 'Cellulose nanofibers' 'Polyurea' 'Pectin'
 'Polybenzoxazine' 'Chitosan' 'Polyester' 'Alginate' 'Carbon nanofibers'
 'Xanthan' 'Guar gum']

--- Second materials ---
Number of categories: 124
['Unknown' 'PVA, GO' 'Lignin' 'PMMA' 'Aramid' 'Silicone resin'
 'Silicone resin, cork' 'Phenolic resin' 'Starch' 'SiO2' 'PVA' 'GO'
 'Cellulose nanofibers' 'Carbon fiber foam' 'Polybutadiene' 'Polyamide'
 'Polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride'
 'Polyaniline' 'Polydopamine' 'Elium resin']

--- Modification ---
Number of categories: 64
['Unknown' 'MTMS treatment' 'Fluorosilan modification' 'Carbonized'
 '3-Aminopropyl(triethoxy)silane treatment' 'Carbon foam' 'TMCS treatment'
 'PET nonwoven' 'HMDS modification' 'Na2CO3' 'Fumed silica'
 'MTES treatment' 'Silicone coating' 'Fluorocarbon modification'
 'NH2-polysiloxane' 'Cellulose cork' 'PEG loading' 'PEG grafting'
 'MTCS treatment' 'Ammonium phosphate']

--- First material class ---
Number of categories: 16
['I' 'H' 'M' 'K' 'G' 'B' 'A' 'F' 'N' 'Q' 'E' 'D' 'R' 'L' 'J' 'C']

--- Second materials class ---
Number of categories: 57
['Unknown' 'E, N' 'F' 'R' 'K' 'S' 'S, L' 'I' 'A' 'E' 'N' 'J' 'G' 'M'
 'A, L' 'A, C, L' 'B' 'N, E' 'R, N' 'N, N']

--- Modification class ---
Number of categories: 8
['Unknown' 'Si' 'Ca' 'Mx' 'Lo' 'Al' 'Ot' 'Si, Lo']

--- Gelation class ---
Number of categories: 9
['cp' 'pp' 'uk' 'ng' 'cc' 'pc' 'cp, pp' 'cc, pp' 'pc, pp']

--- Solvent class ---
Number of categories: 8
['ow' 'al' 'or' 'uk' 'wa' 'al, wa' 'or, wa' 'ow, wa']

--- Process ---
Number of categories: 2193
['Resorcinol-formaldehyde-NaCO3 solution'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 50)'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 200)'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 300)'
 'Phenolic novolak + furfural + catalyst (aromatic acid Q2001)'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 120 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 120 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 120 °C'
 "Saccharose + 4,4'-methylenebis(phenylisocyanate) in DMSO-EtAc (dm < 10) + Dabco TMR (catalyst)"
 "Saccharose + 4,4'-methylenebis(phenylisocyanate) in DMSO-EtAc (dm > 10) + Dabco TMR (catalyst)"
 "Pentaerythritol + 4,4'-methylenebis(phenylisocyanate) in DMSO-EtAc + Dabco TMR (catalyst)"
 'Dicyclopentadiene in toluene + Ru (catalyst/DCPD = 0.0025 wt fr, target density = 0.06 g/cm3)'
 'Dicyclopentadiene in toluene + Ru (catalyst/DCPD = 0.005 wt fr, target density = 0.06 g/cm3)'
 'Dicyclopentadiene in toluene + Ru (catalyst/DCPD = 0.01 wt fr, target density = 0.06 g/cm3)']

--- Gelation mechanism ---
Number of categories: 29
['Chemical (polymerization)' 'Physical (antisolvent)'
 'Physical (temperature)' 'Unknown' 'Physical (aggregation)' 'No gelation'
 'Physical (pH)' 'Chemical (aldehyde)' 'Physical (antisolvent, pH)'
 'Physical (supermolecular)'
 'Chemical (polymerization) and physical (antisolvent)' 'Physical (Mn+)'
 'Physical (aggregation)?' 'Physical?'
 'Chemical (epoxy) and physical (antisolvent)' 'Chemical (isocyanate)'
 'Chemical (isocyanate) and physical (pH)' 'Chemical (epoxy)' 'Physical'
 'Physical (Mn+, pH)']

--- Final solvent ---
Number of categories: 31
['Acetone' 'Methanol' 'Dichloromethane' 'Ethyl acetate' 'Cyclohexane'
 'Ethanol' 'Unknown' 'Water' 't-Butanol' 'Isopropanol' 'Acetonitrile'
 'Toluene' 'Methanol-water?' 'DMSO?' 'Isopropanol?' 'DMAc?' 'scCO2'
 'Pentane' 'Water?' 'Heptane']

--- Drying details ---
Number of categories: 12
['SCD' 'SCD (methanol)' 'FD' 'SCD?' 'APD' 'spray-FD' 'VD' 'APD (60 °C)'
 'Foaming' 'APD?' 'SCD (ethanol)' 'FD (-20 °C)']

--- Post drying treatment ---
Number of categories: 138
['Unknown' 'Post-treatment with cold plasma' 'Post-MTMS treatment'
 'Post-calcination at 200 °C' 'Post-compression treatment'
 'Post-compositing with silicone' 'Post-compositing with cork (5%)'
 'Post-compositing with cork (10%)' 'Post-compositing with cork (15%)'
 'Post-compositing with cork (20%)' 'Post-immersion of PMMA'
 'Post-treatment with tridecafluoro-1,1,2,2-tetrahydrooctyl)-trichlorosilane'
 'Post-compositing with polyamide' 'Post-calcination at 1000 °C'
 'Post-compositing with polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride (1%), FD'
 'Post-compositing with polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride (2%), FD'
 'Post-compositing with polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride (3%), FD'
 'Post-immersion into elium resin' 'Post-compositing with polyaniline'
 'Post-heat treatment at 170 °C']

--- Post-drying cross-linking ---
Number of categories: 4
['Unknown' 'Chemical (ester)' 'Physical (Mn+)' 'Chemical (polymerization)']

--- SEM ---
Number of categories: 21
['Unknown' 'Mesoporous (nanoparticulate)' 'Macroporous (particulate)'
 'Mesoporous (nanofibrous and nanoparticulate)' 'Macroporous (fibrous)'
 'Macroporous (flakes)' 'Macroporous (fibrous and flakes)'
 'Mesoporous (nanofibrous)' 'Macroporous (flakes and particulate)'
 'Macroporous (fibrous and particulate)' 'Macroporous (nanofibrous)'
 'Macroporous (fibrous and nanoparticulate)'
 'Macroporous (cellular and fibrous)' 'Macroporous (nanoparticulate)'
 'Macroporous (cellular and particulate)' 'Macroporous (cellular)'
 'Macroporous (cellular and nanoparticulate)'
 'Macroporous (cellular and nanofibrous)'
 'Macroporous (nanofibrous and particulate)'
 'Mesoporous (nanoparticulate) and macroporous foam']

--- Thermal method ---
Number of categories: 4
['Transient' 'Steady state' 'Unknown' 'Estimation']

--- Thermal method detail ---
Number of categories: 15
['Hot wire' 'HFM' 'Flash' 'Unknown' 'Hot disk' 'GHP' 'TWA' 'Needle probe'
 'DSC' 'IR microscopy?' 'Hot strip?' 'In house' 'Hot disk?'
 'In house, HFM' 'hot disk']

In [73]:

# Remove leading and trailing whitespace from categorical variables

categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = df[col].str.strip()

# Display again categories and number of unique values
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(f"Number of categories: {df[col].nunique()}")
    print(df[col].unique()[:20])

--- Drying ---
Number of categories: 5
['SCD' 'FD' 'APD' 'VD' 'Foaming']

--- Purpose ---
Number of categories: 28
['Thermal insulation' 'Not specific'
 'Sound insulation, thermal insulation' 'Adsorbent' 'Filters' 'Separation'
 'Adsorbent (gas)' 'Thermoelectric devices' 'Steam generation'
 'Separation, thermal insulation' 'Adsorbent, thermal insulation'
 'PCM support' 'Separation, thermal Insulation' 'Sound insulation'
 'Filters, thermal insulation' 'Sensors, thermal insulation'
 'Optoelectronic devices' 'Shield, thermal insulation' 'Packaging'
 'Adsorbent (gas), sensors']

--- Shape ---
Number of categories: 10
['Monolith' 'Fibers, monolith' 'Sheet' 'Fibers' 'Monolith, sheet'
 'Monolith (3D)' 'Beads, monolith' 'Beads' 'FIbers' 'Coating']

--- First materials ---
Number of categories: 90
['RF' 'Phenolic resin' 'Polyisocyanurate' 'Polyurethane'
 'Polydicyclopentadiene' 'Poly(urea-urethane)' 'Aramid fibers' 'Polyimide'
 'Lignocellulose' 'Cellulose' 'Cellulose nanofibers' 'Polyurea' 'Pectin'
 'Polybenzoxazine' 'Chitosan' 'Polyester' 'Alginate' 'Carbon nanofibers'
 'Xanthan' 'Guar gum']

--- Second materials ---
Number of categories: 124
['Unknown' 'PVA, GO' 'Lignin' 'PMMA' 'Aramid' 'Silicone resin'
 'Silicone resin, cork' 'Phenolic resin' 'Starch' 'SiO2' 'PVA' 'GO'
 'Cellulose nanofibers' 'Carbon fiber foam' 'Polybutadiene' 'Polyamide'
 'Polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride'
 'Polyaniline' 'Polydopamine' 'Elium resin']

--- Modification ---
Number of categories: 64
['Unknown' 'MTMS treatment' 'Fluorosilan modification' 'Carbonized'
 '3-Aminopropyl(triethoxy)silane treatment' 'Carbon foam' 'TMCS treatment'
 'PET nonwoven' 'HMDS modification' 'Na2CO3' 'Fumed silica'
 'MTES treatment' 'Silicone coating' 'Fluorocarbon modification'
 'NH2-polysiloxane' 'Cellulose cork' 'PEG loading' 'PEG grafting'
 'MTCS treatment' 'Ammonium phosphate']

--- First material class ---
Number of categories: 16
['I' 'H' 'M' 'K' 'G' 'B' 'A' 'F' 'N' 'Q' 'E' 'D' 'R' 'L' 'J' 'C']

--- Second materials class ---
Number of categories: 57
['Unknown' 'E, N' 'F' 'R' 'K' 'S' 'S, L' 'I' 'A' 'E' 'N' 'J' 'G' 'M'
 'A, L' 'A, C, L' 'B' 'N, E' 'R, N' 'N, N']

--- Modification class ---
Number of categories: 8
['Unknown' 'Si' 'Ca' 'Mx' 'Lo' 'Al' 'Ot' 'Si, Lo']

--- Gelation class ---
Number of categories: 9
['cp' 'pp' 'uk' 'ng' 'cc' 'pc' 'cp, pp' 'cc, pp' 'pc, pp']

--- Solvent class ---
Number of categories: 8
['ow' 'al' 'or' 'uk' 'wa' 'al, wa' 'or, wa' 'ow, wa']

--- Process ---
Number of categories: 2193
['Resorcinol-formaldehyde-NaCO3 solution'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 50)'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 200)'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 300)'
 'Phenolic novolak + furfural + catalyst (aromatic acid Q2001)'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 120 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 120 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 120 °C'
 "Saccharose + 4,4'-methylenebis(phenylisocyanate) in DMSO-EtAc (dm < 10) + Dabco TMR (catalyst)"
 "Saccharose + 4,4'-methylenebis(phenylisocyanate) in DMSO-EtAc (dm > 10) + Dabco TMR (catalyst)"
 "Pentaerythritol + 4,4'-methylenebis(phenylisocyanate) in DMSO-EtAc + Dabco TMR (catalyst)"
 'Dicyclopentadiene in toluene + Ru (catalyst/DCPD = 0.0025 wt fr, target density = 0.06 g/cm3)'
 'Dicyclopentadiene in toluene + Ru (catalyst/DCPD = 0.005 wt fr, target density = 0.06 g/cm3)'
 'Dicyclopentadiene in toluene + Ru (catalyst/DCPD = 0.01 wt fr, target density = 0.06 g/cm3)']

--- Gelation mechanism ---
Number of categories: 29
['Chemical (polymerization)' 'Physical (antisolvent)'
 'Physical (temperature)' 'Unknown' 'Physical (aggregation)' 'No gelation'
 'Physical (pH)' 'Chemical (aldehyde)' 'Physical (antisolvent, pH)'
 'Physical (supermolecular)'
 'Chemical (polymerization) and physical (antisolvent)' 'Physical (Mn+)'
 'Physical (aggregation)?' 'Physical?'
 'Chemical (epoxy) and physical (antisolvent)' 'Chemical (isocyanate)'
 'Chemical (isocyanate) and physical (pH)' 'Chemical (epoxy)' 'Physical'
 'Physical (Mn+, pH)']

--- Final solvent ---
Number of categories: 31
['Acetone' 'Methanol' 'Dichloromethane' 'Ethyl acetate' 'Cyclohexane'
 'Ethanol' 'Unknown' 'Water' 't-Butanol' 'Isopropanol' 'Acetonitrile'
 'Toluene' 'Methanol-water?' 'DMSO?' 'Isopropanol?' 'DMAc?' 'scCO2'
 'Pentane' 'Water?' 'Heptane']

--- Drying details ---
Number of categories: 12
['SCD' 'SCD (methanol)' 'FD' 'SCD?' 'APD' 'spray-FD' 'VD' 'APD (60 °C)'
 'Foaming' 'APD?' 'SCD (ethanol)' 'FD (-20 °C)']

--- Post drying treatment ---
Number of categories: 137
['Unknown' 'Post-treatment with cold plasma' 'Post-MTMS treatment'
 'Post-calcination at 200 °C' 'Post-compression treatment'
 'Post-compositing with silicone' 'Post-compositing with cork (5%)'
 'Post-compositing with cork (10%)' 'Post-compositing with cork (15%)'
 'Post-compositing with cork (20%)' 'Post-immersion of PMMA'
 'Post-treatment with tridecafluoro-1,1,2,2-tetrahydrooctyl)-trichlorosilane'
 'Post-compositing with polyamide' 'Post-calcination at 1000 °C'
 'Post-compositing with polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride (1%), FD'
 'Post-compositing with polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride (2%), FD'
 'Post-compositing with polystyrene-b-poly(ethylene-butylene)-b-polystyrene-g-maleic anhydride (3%), FD'
 'Post-immersion into elium resin' 'Post-compositing with polyaniline'
 'Post-heat treatment at 170 °C']

--- Post-drying cross-linking ---
Number of categories: 4
['Unknown' 'Chemical (ester)' 'Physical (Mn+)' 'Chemical (polymerization)']

--- SEM ---
Number of categories: 21
['Unknown' 'Mesoporous (nanoparticulate)' 'Macroporous (particulate)'
 'Mesoporous (nanofibrous and nanoparticulate)' 'Macroporous (fibrous)'
 'Macroporous (flakes)' 'Macroporous (fibrous and flakes)'
 'Mesoporous (nanofibrous)' 'Macroporous (flakes and particulate)'
 'Macroporous (fibrous and particulate)' 'Macroporous (nanofibrous)'
 'Macroporous (fibrous and nanoparticulate)'
 'Macroporous (cellular and fibrous)' 'Macroporous (nanoparticulate)'
 'Macroporous (cellular and particulate)' 'Macroporous (cellular)'
 'Macroporous (cellular and nanoparticulate)'
 'Macroporous (cellular and nanofibrous)'
 'Macroporous (nanofibrous and particulate)'
 'Mesoporous (nanoparticulate) and macroporous foam']

--- Thermal method ---
Number of categories: 4
['Transient' 'Steady state' 'Unknown' 'Estimation']

--- Thermal method detail ---
Number of categories: 15
['Hot wire' 'HFM' 'Flash' 'Unknown' 'Hot disk' 'GHP' 'TWA' 'Needle probe'
 'DSC' 'IR microscopy?' 'Hot strip?' 'In house' 'Hot disk?'
 'In house, HFM' 'hot disk']

First material class,A,B,C,D,E,F,G,H,I,J,K,L,M,N,Q,R
First materials,,,,,,,,,,,,,,,,
Agar,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Agarose,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alginate,85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Aramid fibers,0,0,0,0,0,0,0,0,0,0,103,0,0,0,0,0
Bacterial cellulose,0,0,0,0,0,0,0,0,0,0,33,0,0,0,0,0
COF,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,0
Carbon fibers,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
Carbon nanofibers,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0
Carboxymethyl cellulose,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Carboxymethyl chitosan,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cellulose,0,149,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cellulose acetate,0,41,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cellulose fibers,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0
Cellulose nanofibers,0,0,0,0,0,0,0,0,0,0,303,0,0,0,0,0
Chitin,0,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chitin nanofibers,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,0
Chitosan,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cyclodextrin,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
EAF fibers,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
GO,0,0,0,0,0,0,0,0,0,0,0,0,0,25,0,0