<a href="https://colab.research.google.com/github/paulagirones/Aerogels_thermal_conductivity/blob/main/aerogels_thermal_conductivity_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aerogels thermal conductivity

# DATA EXPLORATION

In [25]:
import pandas as pd
import numpy as np

# Load the dataset
df_raw = pd.read_csv('20250220_dataset.csv')

# Working copy
df = df_raw.copy()
# Inspect the first rows
print("First 5 rows:")
display(df.head())

# Display information about the dataset
print("\nDataset information:")
df.info()

First 5 rows:

,Entry,Drying,Purpose,Shape,First materials,Second materials,Modification,First material class,Second materials class,Modification class,...,BET surface area m2/g,BJH pore size nm,BJH pore volume (total) cm3/g,compression elastic modulus MPa,SEM,Thermal conductivity W/(m K),Thermal method,Thermal method detail,Unnamed: 28,Unnamed: 29
0,1,SCD,Not specific,Monolith?,Soda soap,NaN,NaN,Q,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,FD,Not specific,Monolith,Polystyrene,NaN,NaN,J,NaN,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16559 entries, 0 to 16558
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Entry                            16559 non-null  int64
 1   Drying                           16559 non-null  object
 2   Purpose                          16559 non-null  object
 3   Shape                            16559 non-null  object
 4   First materials                  16559 non-null  object
 5   Second materials                 6368 non-null   object
 6   Modification                     3086 non-null   object
 7   First material class             16559 non-null  object
 8   Second materials class           6368 non-null   object
 9   Modification class               3082 non-null   object
 10  Gelation class                   16559 non-null  object
 11  Solvent class                    16559 non-null  object
 12  Process                          16559 non-null  object
 13  Gelation mechanism               16559 non-null  object
 14  Final solvent                    16559 non-null  object
 15  Drying details                   16559 non-null  object
 16  Post drying treatment            3295 non-null   object
 17  Post-drying cross-linking        495 non-null    object
 18  Envelope density g/cm3           10755 non-null  float64
 19  Porosity                         7122 non-null   object
 20  BET surface area m2/g            7483 non-null   float64
 21  BJH pore size nm                 1012 non-null   float64
 22  BJH pore volume (total) cm3/g    2479 non-null   float64
 23  compression elastic modulus MPa  3001 non-null   float64
 24  SEM                              15605 non-null  object
 25  Thermal conductivity W/(m K)     2484 non-null   float64
 26  Thermal method                   2493 non-null   object
 27  Thermal method detail            2490 non-null   object
 28  Unnamed: 28                      0 non-null      float64
 29  Unnamed: 29                      29 non-null     object
dtypes: float64(7), int64(1), object(22)
memory usage: 3.8+ MB

# CLEANING AND PRE-PROCESSING

In [26]:
# Check Porosity type
print('Porosity type:')
print(df['Porosity'].dtype)
print(df['Porosity'].unique()[:20])

# Check SEM type
print('SEM type:')
print(df['SEM'].dtype)
print(df['SEM'].unique()[:20])


# Check Unnamed:29 type and content
print('Unnamed: 29 column content:')
print(df['Unnamed: 29'].dtype)
print(df['Unnamed: 29'].unique())

Porosity type:
object
[nan '95%' '94%' '98%' '96%' '97%' '65%' '74.38%' '80.75%' '84.19%'
 '88.06%' '87.45%' '82.64%' '78.32%' '67.97%' '32.80%' '48.20%' '53.70%'
 '59.30%' '65.90%']
SEM type:
object
[nan 'Mesoporous (nanoparticulate)' 'Macroporous (cellular)' 'Mesoporous?'
 'Macroporous (flakes)' 'Macroporous (particulate)'
 'Macroporous (fibrous)' 'Macroporous (fibrous and particulate)'
 'Mesoporous (nanofibrous)' 'Microparticles'
 'Macroporous (cellular and fibrous)'
 'Mesoporous (nanofibrous and nanoparticulate)'
 'Macroporous (cellular and flakes)' 'Macroporous (fibrous and flakes)'
 'Macroporous (nanoparticulate)' 'Macroporous (cellular and particulate)'
 'Macroporous (flakes and particulate)' 'Macroporous' 'Macroporous?'
 'Macroporous (nanofibrous)']
Unnamed: 29 column content:
object
[nan 'kokoko' 'koko' 'kokokoko' 'kokokokoko']

In [27]:
#Fix porosity type (it is numeric)
df['Porosity'] = (
    df['Porosity']
    .str.replace('%', '', regex=False)
    .astype(float)
)

display(df['Porosity'].describe())

# Remove empty and wrong columns
df = df.drop(columns=['Unnamed: 28', 'Unnamed: 29'])

count    7122.000000
mean       87.895411
std        14.065184
min         0.530000
25%        85.000000
50%        92.500000
75%        97.100000
max       100.000000
Name: Porosity, dtype: float64

In [28]:
# Check missing values
missing = pd.DataFrame({
    'Missing values': df.isna().sum(),
    'Missing (%)': df.isna().mean() * 100
})
display(missing.sort_values('Missing (%)', ascending=False))

# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")

                                 Missing values  Missing (%)
Post-drying cross-linking                 16064    97.010689
BJH pore size nm                          15547    93.888520
BJH pore volume (total) cm3/g             14080    85.029289
Thermal conductivity W/(m K)              14075    84.999094
Thermal method detail                     14069    84.962860
Thermal method                            14066    84.944743
compression elastic modulus MPa           13558    81.876925
Modification class                        13477    81.387765
Modification                              13473    81.363609
Post drying treatment                     13264    80.101455
Second materials                          10191    61.543571
Second materials class                    10191    61.543571
Porosity                                   9437    56.990156
BET surface area m2/g                      9076    54.810073
Envelope density g/cm3                     5804    35.050426
SEM                                         954     5.761217
Entry                                         0     0.000000
Drying                                        0     0.000000
Purpose                                       0     0.000000
Shape                                         0     0.000000
Solvent class                                 0     0.000000
Gelation class                                0     0.000000
First materials                               0     0.000000
First material class                          0     0.000000
Process                                       0     0.000000
Gelation mechanism                            0     0.000000
Final solvent                                 0     0.000000
Drying details                                0     0.000000

Duplicate rows: 0

In [35]:
#Rename columns
df = df.rename(columns={
    'Thermal conductivity W/(m K)': 'Thermal_conductivity',
    'Envelope density g/cm3': 'Density',
    'BET surface area m2/g': 'BET',
    'BJH pore size nm': 'Pore_size',
    'BJH pore volume (total) cm3/g': 'Pore_volume',
    'compression elastic modulus MPa': 'Elastic_modulus'
})

# Remove samples without a measured thermal conductivity (our target)
df = df.dropna(subset=['Thermal_conductivity'])

# Display categories and number of unique values
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(f"Number of categories: {df[col].nunique()}")
    print(df[col].unique()[:10])

--- Drying ---
Number of categories: 5
['SCD' 'FD' 'APD' 'VD' 'Foaming']

--- Purpose ---
Number of categories: 28
['Thermal insulation' 'Not specific'
 'Sound insulation, thermal insulation' 'Adsorbent' 'Filters' 'Separation'
 'Adsorbent (gas)' 'Thermoelectric devices' 'Steam generation'
 'Separation, thermal insulation']

--- Shape ---
Number of categories: 10
['Monolith' 'Fibers, monolith' 'Sheet' 'Fibers' 'Monolith, sheet'
 'Monolith (3D)' 'Beads, monolith' 'Beads' 'FIbers' 'Coating']

--- First materials ---
Number of categories: 90
['RF' 'Phenolic resin' 'Polyisocyanurate' 'Polyurethane'
 'Polydicyclopentadiene' 'Poly(urea-urethane)' 'Aramid fibers' 'Polyimide'
 'Lignocellulose' 'Cellulose']

--- Second materials ---
Number of categories: 123
[nan 'PVA, GO' 'Lignin' 'PMMA' 'Aramid' 'Silicone resin'
 'Silicone resin, cork' 'Phenolic resin' 'Starch' 'SiO2']

--- Modification ---
Number of categories: 63
[nan 'MTMS treatment' 'Fluorosilan modification' 'Carbonized'
 '3-Aminopropyl(triethoxy)silane treatment' 'Carbon foam' 'TMCS treatment'
 'PET nonwoven' 'HMDS modification' 'Na2CO3']

--- First material class ---
Number of categories: 16
['I' 'H' 'M' 'K' 'G' 'B' 'A' 'F' 'N' 'Q']

--- Second materials class ---
Number of categories: 56
[nan 'E, N' 'F' 'R' 'K' 'S' 'S, L' 'I' 'A' 'E']

--- Modification class ---
Number of categories: 7
[nan 'Si' 'Ca' 'Mx' 'Lo' 'Al' 'Ot' 'Si, Lo']

--- Gelation class ---
Number of categories: 9
['cp' 'pp' 'uk' 'ng' 'cc' 'pc' 'cp, pp' 'cc, pp' 'pc, pp']

--- Solvent class ---
Number of categories: 8
['ow' 'al' 'or' 'uk' 'wa' 'al, wa' 'or, wa' 'ow, wa']

--- Process ---
Number of categories: 2193
['Resorcinol-formaldehyde-NaCO3 solution'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 50)'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 200)'
 'Resorcinol-formaldehyde-NaCO3 solution (R/C = 300)'
 'Phenolic novolak + furfural + catalyst (aromatic acid Q2001)'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 90) in dichloromethane, cured at 80 °C'
 'Isocyanurate monomers + catalyst (RC = 50) in dichloromethane, cured at 100 °C'
 'Isocyanurate monomers + catalyst (RC = 70) in dichloromethane, cured at 100 °C']

--- Gelation mechanism ---
Number of categories: 29
['Chemical (polymerization)' 'Physical (antisolvent)'
 'Physical (temperature)' 'Unknown' 'Physical (aggregation)' 'No gelation'
 'Physical (pH)' 'Chemical (aldehyde)' 'Physical (antisolvent, pH)'
 'Physical (supermolecular)']

--- Final solvent ---
Number of categories: 31
['Acetone' 'Methanol' 'Dichloromethane' 'Ethyl acetate' 'Cyclohexane'
 'Ethanol' 'Unknown' 'Water' 't-Butanol' 'Isopropanol']

--- Drying details ---
Number of categories: 12
['SCD' 'SCD (methanol)' 'FD' 'SCD?' 'APD' 'spray-FD' 'VD' 'APD (60 °C)'
 'Foaming' 'APD?']

--- Post drying treatment ---
Number of categories: 136
[nan 'Post-treatment with cold plasma' 'Post-MTMS treatment'
 'Post-calcination at 200 °C' 'Post-compression treatment'
 'Post-compositing with silicone' 'Post-compositing with cork (5%)'
 'Post-compositing with cork (10%)' 'Post-compositing with cork (15%)'
 'Post-compositing with cork (20%)']

--- Post-drying cross-linking ---
Number of categories: 3
[nan 'Chemical (ester)' 'Physical (Mn+)' 'Chemical (polymerization)']

--- SEM ---
Number of categories: 20
[nan 'Mesoporous (nanoparticulate)' 'Macroporous (particulate)'
 'Mesoporous (nanofibrous and nanoparticulate)' 'Macroporous (fibrous)'
 'Macroporous (flakes)' 'Macroporous (fibrous and flakes)'
 'Mesoporous (nanofibrous)' 'Macroporous (flakes and particulate)'
 'Macroporous (fibrous and particulate)']

--- Thermal method ---
Number of categories: 4
['Transient' 'Steady state' 'Unknown' 'Estimation']

--- Thermal method detail ---
Number of categories: 15
['Hot wire' 'HFM' 'Flash' 'Unknown' 'Hot disk' 'GHP' 'TWA' 'Needle probe'
 'DSC' 'IR microscopy?']

In [36]:

# Remove leading and trailing whitespace from categorical variables
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = df[col].str.strip()

# Check for potential inconsistencies caused by capitalization
for col in categorical_columns:
    normalized = (
        df[col]
        .str.lower()
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )

    print(
        f"{col}: "
        f"{df[col].nunique()} original -> "
        f"{normalized.nunique()} normalized categories"
    )

Drying: 5 original -> 5 normalized categories
Purpose: 28 original -> 27 normalized categories
Shape: 10 original -> 9 normalized categories
First materials: 90 original -> 90 normalized categories
Second materials: 123 original -> 122 normalized categories
Modification: 63 original -> 63 normalized categories
First material class: 16 original -> 16 normalized categories
Second materials class: 56 original -> 56 normalized categories
Modification class: 7 original -> 7 normalized categories
Gelation class: 9 original -> 9 normalized categories
Solvent class: 8 original -> 8 normalized categories
Process: 2193 original -> 2193 normalized categories
Gelation mechanism: 29 original -> 28 normalized categories
Final solvent: 31 original -> 31 normalized categories
Drying details: 12 original -> 12 normalized categories
Post drying treatment: 136 original -> 136 normalized categories
Post-drying cross-linking: 3 original -> 3 normalized categories
SEM: 20 original -> 20 normalized categories
Thermal method: 4 original -> 4 normalized categories
Thermal method detail: 15 original -> 14 normalized categories

In [39]:
# Find categories that differ only by capitalization or whitespace

for col in categorical_columns:

    normalized = (
        df[col]
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
        .str.lower()
    )

    temp = pd.DataFrame({
        'original': df[col],
        'normalized': normalized
    }).drop_duplicates()

    duplicates = (
        temp.groupby('normalized')['original']
        .agg(list)
    )

    duplicates = duplicates[
        duplicates.apply(lambda x: len(x) > 1)
    ]

    if not duplicates.empty:
        print(f"\n--- {col} ---")
        for normalized_value, original_values in duplicates.items():
            print(f"{original_values} -> '{normalized_value}'")

--- Purpose ---
['Separation, thermal insulation', 'Separation, thermal Insulation'] -> 'separation, thermal insulation'

--- Shape ---
['Fibers', 'FIbers'] -> 'fibers'

--- Second materials ---
['Aramid fibers, MXene', 'Aramid fibers, Mxene'] -> 'aramid fibers, mxene'

--- Gelation mechanism ---
['No gelation', 'NO gelation'] -> 'no gelation'

--- Thermal method detail ---
['Hot disk', 'hot disk'] -> 'hot disk'

In [40]:
# Correct inconsistent categorical values

corrections = {
    'Purpose': {
        'Separation, thermal Insulation': 'Separation, thermal insulation'
    },
    'Shape': {
        'FIbers': 'Fibers'
    },
    'Second materials': {
        'Aramid fibers, Mxene': 'Aramid fibers, MXene'
    },
    'Gelation mechanism': {
        'NO gelation': 'No gelation'
    },
    'Thermal method detail': {
        'hot disk': 'Hot disk'
    }
}

for col, replacements in corrections.items():
    df[col] = df[col].replace(replacements)

In [41]:
# Check categorical variables after corrections

for col in corrections:
    print(f"\n--- {col} ---")
    print(f"Number of categories: {df[col].nunique()}")
    print(df[col].value_counts())
    # Check for remaining capitalization inconsistencies

for col in categorical_columns:
    normalized = (
        df[col]
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
        .str.lower()
    )

    print(
        f"{col}: "
        f"{df[col].nunique()} original categories -> "
        f"{normalized.nunique()} normalized categories"
    )

--- Purpose ---
Number of categories: 27
Purpose
Thermal insulation                               1808
Not specific                                      184
Steam generation                                   58
Separation, thermal insulation                     57
Sound insulation, thermal insulation               54
Separation                                         34
PCM support                                        33
Shield                                             33
Optoelectronic devices                             32
Sound insulation                                   25
Filters                                            23
Shield, thermal insulation                         19
Scaffold, thermal insulation                       18
Filters, thermal insulation                        16
Adsorbent, thermal insulation                      16
Thermoelectric devices                             15
Packaging                                          13
Adsorbent                                           8
Adsorbent (gas)                                     6
Sensors                                             6
Batteries                                           5
Antibacterial                                       5
Adsorbent (gas), sensors                            4
Capacitors                                          4
Filters, sound insulation, thermal insulation       4
Sensors, thermal insulation                         3
Wound dressing                                      1
Name: count, dtype: int64

--- Shape ---
Number of categories: 9
Shape
Monolith            2182
Sheet                137
Fibers                67
Monolith (3D)         58
Monolith, sheet       16
Beads                 11
Fibers, monolith       6
Beads, monolith        6
Coating                1
Name: count, dtype: int64

--- Second materials ---
Number of categories: 122
Second materials
PVA                       184
GO                        101
CNT                        55
Polyurethane               38
Cellulose nanofibers       28
                         ...
Polypyrrole, CNT            1
Alginate, CNT               1
Agarose                     1
Activated carbon            1
Polyacrylonitrile, CNT      1
Name: count, Length: 122, dtype: int64

--- Gelation mechanism ---
Number of categories: 28
Gelation mechanism
Chemical (polymerization)                               984
No gelation                                             808
Physical (antisolvent)                                  203
Physical (aggregation)                                   97
Chemical (aldehyde)                                      71
Physical (temperature)                                   65
Physical (pH)                                            59
Physical (Mn+)                                           54
Physical?                                                27
Chemical (isocyanate)                                    22
No gelation?                                             18
Physical (electrostatic)                                 11
Chemical?                                                 9
Chemical (polymerization)?                                6
Physical                                                  6
Physical (aggregation)?                                   5
Physical (phosphate)                                      5
Chemical (epoxy) and physical (antisolvent)               5
Chemical (epoxy)                                          5
Chemical (polymerization) and physical (antisolvent)      4
Chemical (divinyl sulfone)                                4
Physical (Mn+, pH)                                        4
Physical (antisolvent, pH)                                4
Unknown                                                   2
Physical (supermolecular)                                 2
Chemical (isocyanate) and physical (pH)                   2
Physical (antisolvent)?                                   1
Physical (antisolvent, Mn+)                               1
Name: count, dtype: int64

--- Thermal method detail ---
Number of categories: 14
Thermal method detail
Hot disk          1220
HFM                381
Hot wire           317
Flash              161
GHP                154
Unknown            108
In house            59
Hot disk?           32
DSC                 11
TWA                 10
Needle probe        10
In house, HFM        8
Hot strip?           6
IR microscopy?       4
Name: count, dtype: int64
Drying: 5 original categories -> 5 normalized categories
Purpose: 27 original categories -> 27 normalized categories
Shape: 9 original categories -> 9 normalized categories
First materials: 90 original categories -> 90 normalized categories
Second materials: 122 original categories -> 122 normalized categories
Modification: 63 original categories -> 63 normalized categories
First material class: 16 original categories -> 16 normalized categories
Second materials class: 56 original categories -> 56 normalized categories
Modification class: 7 original categories -> 7 normalized categories
Gelation class: 9 original categories -> 9 normalized categories
Solvent class: 8 original categories -> 8 normalized categories
Process: 2193 original categories -> 2193 normalized categories
Gelation mechanism: 28 original categories -> 28 normalized categories
Final solvent: 31 original categories -> 31 normalized categories
Drying details: 12 original categories -> 12 normalized categories
Post drying treatment: 136 original categories -> 136 normalized categories
Post-drying cross-linking: 3 original categories -> 3 normalized categories
SEM: 20 original categories -> 20 normalized categories
Thermal method: 4 original categories -> 4 normalized categories
Thermal method detail: 14 original categories -> 14 normalized categories

In [37]:
# Check categorical variables
for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(f"Number of categories: {df[col].nunique()}")
    print(df[col].value_counts().head(20))

--- Drying ---
Number of categories: 5
Drying
FD         1347
SCD         851
APD         276
VD            7
Foaming       3
Name: count, dtype: int64

--- Purpose ---
Number of categories: 28
Purpose
Thermal insulation                      1808
Not specific                             184
Steam generation                          58
Sound insulation, thermal insulation      54
Separation, thermal insulation            47
Separation                                34
PCM support                               33
Shield                                    33
Optoelectronic devices                    32
Sound insulation                          25
Filters                                   23
Shield, thermal insulation                19
Scaffold, thermal insulation              18
Filters, thermal insulation               16
Adsorbent, thermal insulation             16
Thermoelectric devices                    15
Packaging                                 13
Separation, thermal Insulation            10
Adsorbent                                  8
Adsorbent (gas)                            6
Name: count, dtype: int64

--- Shape ---
Number of categories: 10
Shape
Monolith            2182
Sheet                137
Fibers                63
Monolith (3D)         58
Monolith, sheet       16
Beads                 11
Fibers, monolith       6
Beads, monolith        6
FIbers                 4
Coating                1
Name: count, dtype: int64

--- First materials ---
Number of categories: 90
First materials
Polyimide                    455
Cellulose nanofibers         303
Cellulose                    149
Polyurethane                 120
RF                           110
Aramid fibers                103
Chitosan                     100
Phenolic resin                96
Alginate                      85
Polybenzoxazine               74
Polyurea                      49
PET                           45
Pectin                        42
Cellulose acetate             41
Glucomannan                   41
Poly(urethane-isocyanate)     39
PVA                           34
Polydicyclopentadiene         33
Bacterial cellulose           33
Carboxymethyl cellulose       30
Name: count, dtype: int64

--- Second materials ---
Number of categories: 123
Second materials
PVA                                        184
GO                                         101
CNT                                         55
Polyurethane                                38
Cellulose nanofibers                        28
Diamond                                     27
Polyimide                                   22
Alginate                                    21
MF                                          20
Carbon fibers                               17
Cellulose                                   15
Hydroxypropyl methylcellulose, PVA, PET     15
Lignin                                      13
Aramid fibers                               12
Polypyrrole                                 11
Carbon                                      10
Poly(aryl ether ketone)                     10
Chitosan                                    10
Starch                                       8
Cellulose nanofibers, PVA                    8
Name: count, dtype: int64

--- Modification ---
Number of categories: 63
Modification
MTMS treatment                                      73
Carbonized                                          19
Carbon foam                                         11
Melamine                                            11
PEG loading                                         11
NH2-polysiloxane                                    10
MTCS treatment                                       8
Hydrophobic SiO2 decoration                          7
MTCS-MTMS treatment                                  6
3-Aminopropyltriethoxysilane modification            6
Borax incorporation                                  6
3-Glycidyloxypropyltrimethoxysilane modification     6
Silicone coating                                     5
PEG grafting                                         5
Ammonium phosphate                                   5
Biguanide phosphonate                                5
3-Glycidoxypropyl)trimethoxysilane modification      5
PET honycomb                                         5
3-Aminopropyl trimethoxysilane modification          5
Cellulose cork                                       5
Name: count, dtype: int64

--- First material class ---
Number of categories: 16
First material class
G    494
K    493
A    342
I    285
H    216
B    209
M    177
F     63
E     39
L     34
J     30
N     30
C     22
Q     18
R     17
D     15
Name: count, dtype: int64

--- Second materials class ---
Number of categories: 56
Second materials class
N          207
E          197
K           68
A           61
H           39
M           34
F           31
I           28
G           24
R           23
A, E, F     15
B           15
J           10
L           10
N, N         8
E, N         8
K, E         8
A, C, L      7
C            7
A, A         6
Name: count, dtype: int64

--- Modification class ---
Number of categories: 7
Modification class
Si        162
Lo         57
Mx         41
Al         20
Ca         19
Ot          1
Si, Lo      1
Name: count, dtype: int64

--- Gelation class ---
Number of categories: 9
Gelation class
cp        990
ng        826
pp        467
cc        111
pc         72
cc, pp      7
pc, pp      5
cp, pp      4
uk          2
Name: count, dtype: int64

--- Solvent class ---
Number of categories: 8
Solvent class
wa        1194
ow         557
al         537
or         100
al, wa      58
uk          27
or, wa      10
ow, wa       1
Name: count, dtype: int64

--- Process ---
Number of categories: 2193
Process
Cellulose nanofiber suspension (frozen)                                                                                                                                                         24
4,4’-Oxydianiline + 3,3’,4,4’-biphenyltetracarboxylic dianhydride + 4,4’-diamino-2,2’-dimethylbiphenyl in DMSO + benzoic anhydride + 2-methyl imidazole + 1,3,5-tris(4-aminophenoxy) benzene    10
Cellulose nanofiber (0.5 wt%) suspension + HCl vapor                                                                                                                                             9
Alginate solution (frozen)                                                                                                                                                                       8
Resorcinol-formaldehyde-Na2CO3 solution                                                                                                                                                          8
Chitosan solution (frozen)                                                                                                                                                                       7
Isocyanatee monomer solution in acetonitrile-THF + pentaerythritol solution in DMSO + catalysts                                                                                                  7
GO suspension (hydrothermal, frozen)                                                                                                                                                             7
Poly(amic acid) solution + TEA (frozen)                                                                                                                                                          7
Resorcinol-formaldehyde-NaOH solution                                                                                                                                                            7
Novolac resin in 2-propanol (heating)                                                                                                                                                            6
Polyimide-polyamideimide fiber suspension + 4,4'-bismaleimidodiphenylmethane (frozen)                                                                                                            6
Cellulose nanofiber suspension + PVA solution (frozen)                                                                                                                                           6
Polyethylene solution in butylated hydroxytoluene-parrafin oil + water (low emissivity)                                                                                                          5
Benzoxazine monomer solution in DMF-HCl                                                                                                                                                          5
Polyethylene solution in butylated hydroxytoluene-parrafin oil + water (high emissivity)                                                                                                         5
Cellulose nanofiber (1%) suspension (frozen)                                                                                                                                                     5
Chitin nanofiber-aramide suspension in KOH-DMSO (frozen)                                                                                                                                         5
Resorcinol-formaldehyde-NaCO3 solution (R/C = 200)                                                                                                                                               5
Resorcinol-formaldehyde-NaCO3 solution (R/C = 300)                                                                                                                                               5
Name: count, dtype: int64

--- Gelation mechanism ---
Number of categories: 29
Gelation mechanism
Chemical (polymerization)                      984
No gelation                                    807
Physical (antisolvent)                         203
Physical (aggregation)                          97
Chemical (aldehyde)                             71
Physical (temperature)                          65
Physical (pH)                                   59
Physical (Mn+)                                  54
Physical?                                       27
Chemical (isocyanate)                           22
No gelation?                                    18
Physical (electrostatic)                        11
Chemical?                                        9
Physical                                         6
Chemical (polymerization)?                       6
Chemical (epoxy) and physical (antisolvent)      5
Chemical (epoxy)                                 5
Physical (aggregation)?                          5
Physical (phosphate)                             5
Physical (antisolvent, pH)                       4
Name: count, dtype: int64

--- Final solvent ---
Number of categories: 31
Final solvent
Water                       1176
Acetone                      507
Ethanol                      372
t-Butanol                     93
t-Butanol-water               47
Isopropanol                   43
Hexane                        34
Unknown                       27
Heptane                       19
Water?                        18
Dichloromethane               17
Acetonitrile                  15
Pentane                       12
Acetone?                      11
Isopropanol?                  11
DMSO                          10
1,2-Dichloroethane-water      10
1,4-Dioxane                   10
Ethanol?                       9
Methanol                       9
Name: count, dtype: int64

--- Drying details ---
Number of categories: 12
Drying details
FD                1326
SCD                852
APD                271
VD                   8
FD (-20 °C)          6
SCD (ethanol)        5
APD?                 4
APD (60 °C)          4
spray-FD             3
Foaming              3
SCD?                 1
SCD (methanol)       1
Name: count, dtype: int64

--- Post drying treatment ---
Number of categories: 136
Post drying treatment
Post-calcination at 300 °C                 51
Post-MTMS treatment                        48
Post-calcination at 400 °C                 18
Post-calcination at 200 °C                 18
Post-calcination at 250 °C                 17
Post-calcination at 380 °C                 15
Post-calcination at 230 °C                 12
Post-compression treatment                 10
Post-calcination at 800 °C                 10
Post-immersion into CaCl2 solution, FD     10
Post-heat treatment                        10
Post-TEA treatment and printing             9
Post-MTMS treatment?                        8
Post-compression                            8
Post-immersion into CaCl2 solution          8
Post-MTCS treatment                         7
Post-compositing with polyurethane foam     7
Post-MTCS-MTMS treatment                    6
Post-hydrophobic SiO2 decoration            6
Post-calcination                            6
Name: count, dtype: int64

--- Post-drying cross-linking ---
Number of categories: 3
Post-drying cross-linking
Physical (Mn+)               24
Chemical (polymerization)     4
Chemical (ester)              2
Name: count, dtype: int64

--- SEM ---
Number of categories: 20
SEM
Macroporous (cellular)                               576
Mesoporous (nanoparticulate)                         489
Macroporous (fibrous)                                328
Macroporous (flakes)                                 293
Macroporous (particulate)                            287
Mesoporous (nanofibrous)                             178
Macroporous (fibrous and flakes)                      87
Mesoporous (nanofibrous and nanoparticulate)          57
Macroporous (cellular and fibrous)                    36
Macroporous (fibrous and particulate)                 25
Macroporous (nanofibrous)                             22
Macroporous (flakes and particulate)                  20
Macroporous (cellular and nanofibrous)                11
Macroporous (nanoparticulate)                         10
Macroporous (cellular and particulate)                 9
Mesoporous (nanoparticulate) and macroporous foam      5
Macroporous (fibrous and nanoparticulate)              4
Macroporous (cellular and nanoparticulate)             1
Macroporous (nanofibrous and particulate)              1
Macroporous (flakes and fibrous)                       1
Name: count, dtype: int64

--- Thermal method ---
Number of categories: 4
Thermal method
Transient       1808
Steady state     581
Unknown           92
Estimation         3
Name: count, dtype: int64

--- Thermal method detail ---
Number of categories: 15
Thermal method detail
Hot disk          1217
HFM                381
Hot wire           317
Flash              161
GHP                154
Unknown            108
In house            59
Hot disk?           32
DSC                 11
TWA                 10
Needle probe        10
In house, HFM        8
Hot strip?           6
IR microscopy?       4
hot disk             3
Name: count, dtype: int64

In [30]:
#Dataset after cleaning
print(f"Dataset after cleaning: {df.shape}")

missing = pd.DataFrame({
    'Missing values': df.isna().sum(),
    'Missing (%)': df.isna().mean() * 100
})
display(missing.sort_values('Missing (%)', ascending=False))

Dataset after cleaning: (2484, 28)

                           Missing values  Missing (%)
Post-drying cross-linking            2454    98.792271
Pore_size                            2324    93.558776
Modification class                   2183    87.882448
Modification                         2179    87.721417
Pore_volume                          2166    87.198068
Post drying treatment                2002    80.595813
Elastic_modulus                      1657    66.706924
Second materials                     1596    64.251208
Second materials class               1596    64.251208
BET                                  1525    61.392915
Porosity                             1079    43.438003
Density                               274    11.030596
SEM                                    44     1.771337
Thermal method detail                   3     0.120773
First materials                         0     0.000000
First material class                    0     0.000000
Entry                                   0     0.000000
Drying                                  0     0.000000
Purpose                                 0     0.000000
Shape                                   0     0.000000
Solvent class                           0     0.000000
Gelation class                          0     0.000000
Final solvent                           0     0.000000
Drying details                          0     0.000000
Process                                 0     0.000000
Gelation mechanism                      0     0.000000
Thermal_conductivity                    0     0.000000
Thermal method                          0     0.000000